name: Build And Push to Dockerhub
on:
  workflow_dispatch:
  push:
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**/*.md'
permissions:
  contents: read
jobs:
  main:
    name: Build Docker Image
    env:
      DOCKER_BUILD_ENABLED: ${{ secrets.DOCKER_BUILD_ENABLED }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push branch
        if: contains(env.DOCKER_BUILD_ENABLED, 'true')
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "bigbluebutton/bbb-libreoffice:${{ github.ref_name }}"
          context: .
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
